import { Injectable } from '@angular/core';
import { Recipe, RecipeCategory, NewsArticle, Product } from '../models';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {

  readonly categories: RecipeCategory[] = [
    { id: '1', name: '健康飲食', slug: 'healthy', description: '營養均衡的健康料理' },
    { id: '2', name: '快速料理', slug: 'quick', description: '15分鐘快速上桌' },
    { id: '3', name: '節慶主題', slug: 'festive', description: '節慶必備料理' },
    { id: '4', name: '餐別與時段', slug: 'mealtime', description: '早午晚餐、下午茶' },
    { id: '5', name: '預算與成本', slug: 'budget', description: '省錢又美味' },
    { id: '6', name: '器具與空間', slug: 'equipment', description: '依器具分類' },
    { id: '7', name: '親子學習', slug: 'family', description: '親子共廚樂趣' },
    { id: '8', name: '便當、外帶', slug: 'bento', description: '便當與外帶料理' },
    { id: '9', name: '時令與永續', slug: 'seasonal', description: '當季食材料理' },
    { id: '10', name: '特殊需求', slug: 'special', description: '素食、低醣、無麩質' },
  ];

  readonly popularRecipes: Recipe[] = [
    {
      id: '1',
      title: '麻婆豆腐',
      description: '香辣濃郁、麻而不嗆，是最經典的川味家常菜之一，滑嫩的豆腐吸附著肉末與豆瓣醬的香氣，一口下去鹹香帶勁、辣中帶麻，讓人忍不住一口白飯接一口。',
      imageUrl: 'https://images.unsplash.com/photo-1582576163090-09d3b6f8a969?w=800',
      cookingTime: 30,
      prepTime: 10,
      servings: 3,
      difficulty: 'easy',
      rating: 4.2,
      ratingCount: 888,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-31',
      ingredients: [
        { name: '盒裝豆腐', amount: '1', unit: '盒' },
        { name: '豬絞肉', amount: '60', unit: '公克' },
        { name: '蔥', amount: '2', unit: '根' },
        { name: '蒜末', amount: '15', unit: '公克' },
        { name: '薑末', amount: '10', unit: '公克' },
      ],
      seasonings: [
        { group: 'A', items: [{ name: '紅辣椒醬', amount: '2 大匙' }] },
        { group: 'B', items: [{ name: '水', amount: '100 c.c.' }, { name: '醬油', amount: '1 茶匙' }] },
      ],
      steps: [
        { stepNumber: 1, description: '豆腐切丁；蔥切花，備用。' },
        { stepNumber: 2, description: '熱鍋，倒入少許油，先以小火爆香蒜末、薑末，再放入豬絞肉炒熟。' },
        { stepNumber: 3, description: '續加紅辣椒醬炒香後加入所有調味料B，待燒開後放入豆腐丁略煮滾。' },
      ],
      kitchenware: [{ id: 'k1', name: 'Woody 木質調磨石陶瓷瓶底深鍋 26cm', imageUrl: '', price: 1800, purchaseUrl: '#' }],
      tags: ['中式經典', '快速料理', '豆腐'],
      categories: ['快速料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['川菜']
    },
    {
      id: '2',
      title: '蔬菜拼盤',
      description: '清爽健康的蔬菜拼盤，富含多種維生素與膳食纖維，是減重與養生的最佳選擇。',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
      cookingTime: 20,
      prepTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 650,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-30',
      ingredients: [{ name: '綠花椰菜', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '橄欖油', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '將所有蔬菜洗淨，切成適當大小。' }],
      kitchenware: [],
      tags: ['健康', '素食'],
      categories: ['健康飲食'],
      mealTypes: ['午餐'],
      cookingStyles: ['西式']
    },
    {
      id: '3',
      title: '橄欖輕食沙拉',
      description: '地中海風味的清爽沙拉，搭配新鮮橄欖與特製油醋醬，營養滿分。',
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
      cookingTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.3,
      ratingCount: 420,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-29',
      ingredients: [{ name: '生菜', amount: '200', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '橄欖油', amount: '3 大匙' }] }],
      steps: [{ stepNumber: 1, description: '生菜洗淨瀝乾，撕成適口大小。' }],
      kitchenware: [],
      tags: ['健康', '輕食'],
      categories: ['健康飲食'],
      mealTypes: ['午餐'],
      cookingStyles: ['地中海料理']
    },
    {
      id: '4',
      title: '炙燒冬菇',
      description: '鮮嫩多汁的炙燒冬菇，簡單調味卻能帶出菇類的原始鮮味。',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
      cookingTime: 25,
      servings: 4,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 320,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-28',
      ingredients: [{ name: '鮮香菇', amount: '300', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '香菇洗淨去蒂。' }],
      kitchenware: [],
      tags: ['素食', '簡單'],
      categories: ['快速料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['日式']
    },
    {
      id: '5',
      title: '凱薩沙拉',
      description: '經典凱薩沙拉，搭配酥脆麵包丁與帕瑪森起司，濃郁美味。',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
      cookingTime: 20,
      servings: 2,
      difficulty: 'easy',
      rating: 4.4,
      ratingCount: 580,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-27',
      ingredients: [{ name: '蘿蔓生菜', amount: '1', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '凱薩醬', amount: '4 大匙' }] }],
      steps: [{ stepNumber: 1, description: '蘿蔓生菜洗淨切段。' }],
      kitchenware: [],
      tags: ['沙拉', '經典'],
      categories: ['健康飲食'],
      mealTypes: ['午餐'],
      cookingStyles: ['美式']
    },
    {
      id: '6',
      title: '番茄炒蛋',
      description: '家常經典番茄炒蛋，酸甜滑嫩，簡單又下飯。',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      cookingTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1200,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-26',
      ingredients: [{ name: '雞蛋', amount: '3', unit: '顆' }, { name: '番茄', amount: '2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '番茄切塊，雞蛋打散備用。' }],
      kitchenware: [],
      tags: ['家常', '下飯', '雞蛋'],
      categories: ['快速料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '7',
      title: '蒜香雞腿排',
      description: '外酥內嫩的蒜香雞腿排，濃郁蒜香搭配多汁雞肉，讓人食指大動。',
      imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
      cookingTime: 35,
      servings: 2,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 890,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-25',
      ingredients: [{ name: '去骨雞腿排', amount: '2', unit: '片' }, { name: '蒜頭', amount: '6', unit: '瓣' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '2 大匙' }, { name: '米酒', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞腿排抹上調味料醃製30分鐘。' }],
      kitchenware: [],
      tags: ['雞肉', '下飯', '便當菜'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '8',
      title: '日式味噌湯',
      description: '溫暖療癒的日式味噌湯，豆腐與海帶芽完美搭配，開啟美好的一天。',
      imageUrl: 'https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800',
      cookingTime: 20,
      servings: 4,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 720,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-24',
      ingredients: [{ name: '嫩豆腐', amount: '1', unit: '盒' }, { name: '海帶芽', amount: '適量', unit: '' }],
      seasonings: [{ group: 'A', items: [{ name: '味噌', amount: '3 大匙' }] }],
      steps: [{ stepNumber: 1, description: '水煮滾後加入豆腐和海帶芽。' }],
      kitchenware: [],
      tags: ['湯品', '健康', '豆腐'],
      categories: ['健康飲食'],
      mealTypes: ['早餐', '午餐'],
      cookingStyles: ['日式']
    },
    {
      id: '9',
      title: '韓式辣炒年糕',
      description: 'Q彈年糕裹上甜辣醬汁，這道韓國街頭小吃讓人一吃就上癮！',
      imageUrl: 'https://images.unsplash.com/photo-1635363638580-c2809d049eee?w=800',
      cookingTime: 25,
      servings: 3,
      difficulty: 'easy',
      rating: 4.8,
      ratingCount: 1560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-23',
      ingredients: [{ name: '韓式年糕', amount: '300', unit: '公克' }, { name: '魚板', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '韓式辣醬', amount: '3 大匙' }, { name: '砂糖', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '年糕泡水軟化備用。' }],
      kitchenware: [],
      tags: ['韓式', '辣', '小吃'],
      categories: ['異國料理'],
      mealTypes: ['點心', '晚餐'],
      cookingStyles: ['韓式']
    },
    {
      id: '10',
      title: '奶油培根義大利麵',
      description: '濃郁奶油醬汁包裹著義大利麵，搭配香脆培根，經典義式風味。',
      imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
      cookingTime: 25,
      servings: 2,
      difficulty: 'medium',
      rating: 4.7,
      ratingCount: 980,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-22',
      ingredients: [{ name: '義大利麵', amount: '200', unit: '公克' }, { name: '培根', amount: '80', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '鮮奶油', amount: '100 ml' }, { name: '帕瑪森起司', amount: '30 公克' }] }],
      steps: [{ stepNumber: 1, description: '義大利麵依包裝指示煮熟。' }],
      kitchenware: [],
      tags: ['義式', '麵食', '奶油'],
      categories: ['異國料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['西式']
    },
    {
      id: '11',
      title: '清蒸鱸魚',
      description: '鮮嫩的鱸魚搭配薑絲蔥花，清蒸方式保留魚肉原始鮮甜。',
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
      cookingTime: 20,
      servings: 4,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-21',
      ingredients: [{ name: '鱸魚', amount: '1', unit: '尾' }, { name: '薑', amount: '適量', unit: '' }],
      seasonings: [{ group: 'A', items: [{ name: '蒸魚醬油', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '鱸魚清洗乾淨，在魚身劃刀。' }],
      kitchenware: [],
      tags: ['清蒸', '海鮮', '健康'],
      categories: ['健康飲食'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '12',
      title: '台式滷肉飯',
      description: '香噴噴的滷肉淋在白飯上，台灣經典國民美食，一碗接一碗停不下來！',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
      cookingTime: 90,
      servings: 6,
      difficulty: 'medium',
      rating: 4.9,
      ratingCount: 2100,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-20',
      ingredients: [{ name: '五花肉', amount: '600', unit: '公克' }, { name: '紅蔥頭', amount: '80', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '4 大匙' }, { name: '冰糖', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '五花肉切成小丁。' }],
      kitchenware: [],
      tags: ['台式', '經典', '滷味'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '13',
      title: '蔬菜咖哩',
      description: '暖胃又營養的蔬菜咖哩，使用當季蔬菜熬煮而成，素食者也能享用。',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
      cookingTime: 45,
      servings: 4,
      difficulty: 'easy',
      rating: 4.4,
      ratingCount: 680,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-19',
      ingredients: [{ name: '馬鈴薯', amount: '2', unit: '顆' }, { name: '紅蘿蔔', amount: '1', unit: '根' }],
      seasonings: [{ group: 'A', items: [{ name: '咖哩塊', amount: '1 盒' }] }],
      steps: [{ stepNumber: 1, description: '馬鈴薯、紅蘿蔔切塊備用。' }],
      kitchenware: [],
      tags: ['咖哩', '素食', '健康'],
      categories: ['健康飲食'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['日式']
    },
    {
      id: '14',
      title: '法式可麗餅',
      description: '薄脆香甜的法式可麗餅，可搭配水果或巧克力醬，完美的下午茶點心。',
      imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800',
      cookingTime: 30,
      servings: 4,
      difficulty: 'medium',
      rating: 4.5,
      ratingCount: 450,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-18',
      ingredients: [{ name: '麵粉', amount: '150', unit: '公克' }, { name: '雞蛋', amount: '2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '砂糖', amount: '2 大匙' }, { name: '鮮奶', amount: '300 ml' }] }],
      steps: [{ stepNumber: 1, description: '將所有材料攪拌均勻成麵糊。' }],
      kitchenware: [],
      tags: ['甜點', '法式', '雞蛋'],
      categories: ['甜點烘焙'],
      mealTypes: ['下午茶', '早餐'],
      cookingStyles: ['西式']
    },
    {
      id: '15',
      title: '泰式打拋豬',
      description: '酸辣開胃的泰式打拋豬，九層塔香氣四溢，配飯超級下飯！',
      imageUrl: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800',
      cookingTime: 20,
      servings: 2,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1100,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-17',
      ingredients: [{ name: '豬絞肉', amount: '200', unit: '公克' }, { name: '九層塔', amount: '1', unit: '把' }],
      seasonings: [{ group: 'A', items: [{ name: '魚露', amount: '2 大匙' }, { name: '蠔油', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '辣椒、蒜頭切末備用。' }],
      kitchenware: [],
      tags: ['泰式', '辣', '快速'],
      categories: ['快速料理', '異國料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['泰式']
    },
    {
      id: '16',
      title: '焗烤馬鈴薯',
      description: '外皮酥脆內層綿密的焗烤馬鈴薯，濃郁起司讓人無法抗拒。',
      imageUrl: 'https://images.unsplash.com/photo-1633436374961-09b92742047b?w=800',
      cookingTime: 50,
      servings: 4,
      difficulty: 'medium',
      rating: 4.5,
      ratingCount: 620,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-16',
      ingredients: [{ name: '馬鈴薯', amount: '4', unit: '顆' }, { name: '培根', amount: '60', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '起司絲', amount: '100 公克' }, { name: '鮮奶油', amount: '50 ml' }] }],
      steps: [{ stepNumber: 1, description: '馬鈴薯洗淨，放入烤箱烤熟。' }],
      kitchenware: [],
      tags: ['焗烤', '馬鈴薯', '起司'],
      categories: ['異國料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['西式']
    },
    {
      id: '17',
      title: '鮭魚茶泡飯',
      description: '日式療癒系料理，鮮嫩鮭魚搭配熱騰騰的茶湯，簡單又美味。',
      imageUrl: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=800',
      cookingTime: 15,
      servings: 1,
      difficulty: 'easy',
      rating: 4.4,
      ratingCount: 380,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-15',
      ingredients: [{ name: '鮭魚', amount: '100', unit: '公克' }, { name: '白飯', amount: '1', unit: '碗' }],
      seasonings: [{ group: 'A', items: [{ name: '柴魚高湯', amount: '300 ml' }] }],
      steps: [{ stepNumber: 1, description: '鮭魚煎熟後撥成小塊。' }],
      kitchenware: [],
      tags: ['日式', '健康', '海鮮'],
      categories: ['快速料理'],
      mealTypes: ['午餐', '宵夜'],
      cookingStyles: ['日式']
    },
    {
      id: '18',
      title: '蒜泥白肉',
      description: '薄片五花肉搭配蒜泥醬汁，清爽不膩口的經典川菜前菜。',
      imageUrl: 'https://images.unsplash.com/photo-1623238912680-26fc5ffb57e4?w=800',
      cookingTime: 40,
      servings: 4,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 520,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-14',
      ingredients: [{ name: '五花肉', amount: '400', unit: '公克' }, { name: '蒜頭', amount: '30', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '3 大匙' }, { name: '香油', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '五花肉整塊放入滾水中煮熟。' }],
      kitchenware: [],
      tags: ['川菜', '冷盤', '豬肉'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    // === 快速料理 ===
    {
      id: '19',
      title: '蔥花蛋餅',
      description: '酥脆的外皮包裹著滑嫩的蛋液，灑上蔥花香氣四溢，早餐首選！',
      imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
      cookingTime: 10,
      servings: 1,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 980,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-13',
      ingredients: [{ name: '蛋餅皮', amount: '1', unit: '張' }, { name: '雞蛋', amount: '1', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '少許' }] }],
      steps: [{ stepNumber: 1, description: '蛋餅皮放入平底鍋，打入雞蛋。' }],
      kitchenware: [],
      tags: ['早餐', '快速', '雞蛋'],
      categories: ['快速料理'],
      mealTypes: ['早餐'],
      cookingStyles: ['中式']
    },
    {
      id: '20',
      title: '涼拌小黃瓜',
      description: '清爽開胃的涼拌小黃瓜，簡單調味就超好吃，夏日必備！',
      imageUrl: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800',
      cookingTime: 10,
      servings: 2,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 720,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-12',
      ingredients: [{ name: '小黃瓜', amount: '2', unit: '條' }, { name: '蒜末', amount: '適量', unit: '' }],
      seasonings: [{ group: 'A', items: [{ name: '醋', amount: '2 大匙' }, { name: '糖', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '小黃瓜拍碎切段。' }],
      kitchenware: [],
      tags: ['涼拌', '快速', '素食'],
      categories: ['快速料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['中式']
    },
    {
      id: '21',
      title: '蒜香炒青菜',
      description: '簡單的蒜香炒青菜，保留蔬菜的鮮脆口感，營養滿分。',
      imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
      cookingTime: 8,
      servings: 2,
      difficulty: 'easy',
      rating: 4.3,
      ratingCount: 560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-11',
      ingredients: [{ name: '空心菜', amount: '300', unit: '公克' }, { name: '蒜頭', amount: '3', unit: '瓣' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '蒜頭切片爆香。' }],
      kitchenware: [],
      tags: ['素食', '快速', '健康'],
      categories: ['快速料理', '健康飲食'],
      mealTypes: ['配菜'],
      cookingStyles: ['中式']
    },
    {
      id: '22',
      title: '皮蛋豆腐',
      description: '冰涼爽口的皮蛋豆腐，淋上醬油膏和香油，經典台式小菜。',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-5ec6a79120b0?w=800',
      cookingTime: 5,
      servings: 2,
      difficulty: 'easy',
      rating: 4.4,
      ratingCount: 480,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-10',
      ingredients: [{ name: '嫩豆腐', amount: '1', unit: '盒' }, { name: '皮蛋', amount: '2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油膏', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '豆腐切塊，皮蛋切瓣。' }],
      kitchenware: [],
      tags: ['涼拌', '快速', '豆腐'],
      categories: ['快速料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['中式']
    },
    {
      id: '23',
      title: '醬燒杏鮑菇',
      description: '口感Q彈的杏鮑菇，用醬油燒出焦香，素食者的最愛！',
      imageUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800',
      cookingTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 620,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-09',
      ingredients: [{ name: '杏鮑菇', amount: '2', unit: '根' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '2 大匙' }, { name: '蠔油', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '杏鮑菇切厚片。' }],
      kitchenware: [],
      tags: ['素食', '快速', '菇類'],
      categories: ['快速料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['中式']
    },
    // === 健康飲食 ===
    {
      id: '24',
      title: '藜麥沙拉',
      description: '超級食物藜麥搭配新鮮蔬菜，高蛋白低熱量的健康選擇。',
      imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800',
      cookingTime: 25,
      servings: 2,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 520,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-08',
      ingredients: [{ name: '藜麥', amount: '100', unit: '公克' }, { name: '小番茄', amount: '10', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '橄欖油', amount: '2 大匙' }, { name: '檸檬汁', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '藜麥洗淨後煮熟放涼。' }],
      kitchenware: [],
      tags: ['健康', '沙拉', '素食'],
      categories: ['健康飲食'],
      mealTypes: ['午餐'],
      cookingStyles: ['西式']
    },
    {
      id: '25',
      title: '雞胸肉沙拉',
      description: '低脂高蛋白的雞胸肉沙拉，健身減脂的最佳夥伴。',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
      cookingTime: 20,
      servings: 1,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 780,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-07',
      ingredients: [{ name: '雞胸肉', amount: '150', unit: '公克' }, { name: '生菜', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '橄欖油', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞胸肉煎熟切片。' }],
      kitchenware: [],
      tags: ['健康', '沙拉', '雞肉'],
      categories: ['健康飲食'],
      mealTypes: ['午餐'],
      cookingStyles: ['西式']
    },
    {
      id: '26',
      title: '蒸蛋',
      description: '滑嫩如布丁的蒸蛋，簡單調味就非常美味，老少咸宜。',
      imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800',
      cookingTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1200,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-06',
      ingredients: [{ name: '雞蛋', amount: '3', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '1/4 茶匙' }] }],
      steps: [{ stepNumber: 1, description: '雞蛋打散加入高湯。' }],
      kitchenware: [],
      tags: ['健康', '雞蛋', '簡單'],
      categories: ['健康飲食', '快速料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['中式']
    },
    {
      id: '27',
      title: '燕麥粥',
      description: '營養豐富的燕麥粥，加入水果和堅果，開啟元氣滿滿的一天。',
      imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800',
      cookingTime: 10,
      servings: 1,
      difficulty: 'easy',
      rating: 4.4,
      ratingCount: 450,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-05',
      ingredients: [{ name: '燕麥片', amount: '50', unit: '公克' }, { name: '牛奶', amount: '200', unit: 'ml' }],
      seasonings: [{ group: 'A', items: [{ name: '蜂蜜', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '燕麥片加牛奶煮滾。' }],
      kitchenware: [],
      tags: ['健康', '早餐', '素食'],
      categories: ['健康飲食'],
      mealTypes: ['早餐'],
      cookingStyles: ['西式']
    },
    {
      id: '28',
      title: '地瓜球',
      description: '外酥內Q的地瓜球，天然食材製作，健康又美味的小點心。',
      imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800',
      cookingTime: 30,
      servings: 4,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 680,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-04',
      ingredients: [{ name: '地瓜', amount: '300', unit: '公克' }, { name: '糯米粉', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '糖', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '地瓜蒸熟壓成泥。' }],
      kitchenware: [],
      tags: ['健康', '點心', '素食'],
      categories: ['健康飲食'],
      mealTypes: ['點心'],
      cookingStyles: ['中式']
    },
    // === 日式料理 ===
    {
      id: '29',
      title: '照燒雞腿',
      description: '甜鹹適中的照燒雞腿，外皮焦香內部多汁，便當必備菜色。',
      imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800',
      cookingTime: 30,
      servings: 2,
      difficulty: 'medium',
      rating: 4.8,
      ratingCount: 1450,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-03',
      ingredients: [{ name: '去骨雞腿', amount: '2', unit: '支' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '3 大匙' }, { name: '味醂', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞腿肉煎至金黃。' }],
      kitchenware: [],
      tags: ['日式', '雞肉', '便當菜'],
      categories: ['日式料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['日式']
    },
    {
      id: '30',
      title: '日式炸豬排',
      description: '酥脆的麵衣包裹著鮮嫩豬排，搭配高麗菜絲和豬排醬，經典日式定食。',
      imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
      cookingTime: 35,
      servings: 2,
      difficulty: 'medium',
      rating: 4.7,
      ratingCount: 1280,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-02',
      ingredients: [{ name: '豬里肌', amount: '2', unit: '片' }, { name: '麵包粉', amount: '適量', unit: '' }],
      seasonings: [{ group: 'A', items: [{ name: '豬排醬', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '豬排用肉槌敲鬆。' }],
      kitchenware: [],
      tags: ['日式', '炸物', '豬肉'],
      categories: ['日式料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['日式']
    },
    {
      id: '31',
      title: '親子丼',
      description: '滑蛋與雞肉的完美搭配，甜鹹醬汁滲入米飯，一碗滿足的日式丼飯。',
      imageUrl: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800',
      cookingTime: 20,
      servings: 1,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 920,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-12-01',
      ingredients: [{ name: '雞腿肉', amount: '100', unit: '公克' }, { name: '雞蛋', amount: '2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '2 大匙' }, { name: '味醂', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞腿肉切塊煮熟。' }],
      kitchenware: [],
      tags: ['日式', '丼飯', '雞肉'],
      categories: ['日式料理', '快速料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['日式']
    },
    {
      id: '32',
      title: '日式咖哩飯',
      description: '濃郁香甜的日式咖哩，加入馬鈴薯和紅蘿蔔，家庭必備料理。',
      imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
      cookingTime: 50,
      servings: 4,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-30',
      ingredients: [{ name: '豬肉', amount: '200', unit: '公克' }, { name: '咖哩塊', amount: '1', unit: '盒' }],
      seasonings: [{ group: 'A', items: [{ name: '水', amount: '600 ml' }] }],
      steps: [{ stepNumber: 1, description: '蔬菜和肉切塊炒香。' }],
      kitchenware: [],
      tags: ['日式', '咖哩', '家常'],
      categories: ['日式料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['日式']
    },
    {
      id: '33',
      title: '壽喜燒',
      description: '甜鹹醬汁煮出的鮮嫩牛肉，搭配各式蔬菜和豆腐，日式火鍋經典。',
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800',
      cookingTime: 40,
      servings: 4,
      difficulty: 'medium',
      rating: 4.8,
      ratingCount: 980,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-29',
      ingredients: [{ name: '牛肉片', amount: '300', unit: '公克' }, { name: '大蔥', amount: '2', unit: '根' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '100 ml' }, { name: '味醂', amount: '50 ml' }] }],
      steps: [{ stepNumber: 1, description: '鍋中放入醬汁煮滾。' }],
      kitchenware: [],
      tags: ['日式', '火鍋', '牛肉'],
      categories: ['日式料理'],
      mealTypes: ['晚餐'],
      cookingStyles: ['日式']
    },
    // === 韓式料理 ===
    {
      id: '34',
      title: '韓式炸雞',
      description: '外酥內嫩的韓式炸雞，沾上甜辣醬或蒜味醬，追劇必備！',
      imageUrl: 'https://images.unsplash.com/photo-1575932444877-5106bee2a599?w=800',
      cookingTime: 45,
      servings: 4,
      difficulty: 'medium',
      rating: 4.9,
      ratingCount: 2100,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-28',
      ingredients: [{ name: '雞翅', amount: '10', unit: '支' }],
      seasonings: [{ group: 'A', items: [{ name: '韓式辣醬', amount: '3 大匙' }, { name: '蜂蜜', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞翅醃製30分鐘。' }],
      kitchenware: [],
      tags: ['韓式', '炸物', '雞肉'],
      categories: ['韓式料理'],
      mealTypes: ['晚餐', '宵夜'],
      cookingStyles: ['韓式']
    },
    {
      id: '35',
      title: '韓式泡菜鍋',
      description: '酸辣開胃的泡菜鍋，加入豆腐和五花肉，寒冷天氣的暖心選擇。',
      imageUrl: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800',
      cookingTime: 30,
      servings: 2,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1340,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-27',
      ingredients: [{ name: '泡菜', amount: '200', unit: '公克' }, { name: '五花肉', amount: '150', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '韓式辣椒粉', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '五花肉炒出油脂。' }],
      kitchenware: [],
      tags: ['韓式', '火鍋', '辣'],
      categories: ['韓式料理'],
      mealTypes: ['晚餐'],
      cookingStyles: ['韓式']
    },
    {
      id: '36',
      title: '韓式拌飯',
      description: '色彩繽紛的韓式拌飯，蔬菜、肉末和蛋黃拌在一起，營養均衡又美味。',
      imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800',
      cookingTime: 35,
      servings: 1,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 890,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-26',
      ingredients: [{ name: '白飯', amount: '1', unit: '碗' }, { name: '牛絞肉', amount: '80', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '韓式辣醬', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '各式蔬菜分別炒熟調味。' }],
      kitchenware: [],
      tags: ['韓式', '拌飯', '健康'],
      categories: ['韓式料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['韓式']
    },
    {
      id: '37',
      title: '韓式煎餅',
      description: '酥脆的韓式煎餅，加入蔬菜和海鮮，沾醬油吃超對味！',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
      cookingTime: 20,
      servings: 2,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 720,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-25',
      ingredients: [{ name: '韭菜', amount: '100', unit: '公克' }, { name: '中筋麵粉', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '1/2 茶匙' }] }],
      steps: [{ stepNumber: 1, description: '麵粉加水調成麵糊。' }],
      kitchenware: [],
      tags: ['韓式', '煎餅', '素食'],
      categories: ['韓式料理', '快速料理'],
      mealTypes: ['點心'],
      cookingStyles: ['韓式']
    },
    {
      id: '38',
      title: '部隊鍋',
      description: '融合韓式風味與美式食材的部隊鍋，泡麵、香腸、起司一鍋滿足。',
      imageUrl: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=800',
      cookingTime: 25,
      servings: 2,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 1100,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-24',
      ingredients: [{ name: '韓國泡麵', amount: '2', unit: '包' }, { name: '午餐肉', amount: '100', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '韓式辣椒粉', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '所有食材放入鍋中。' }],
      kitchenware: [],
      tags: ['韓式', '火鍋', '辣'],
      categories: ['韓式料理'],
      mealTypes: ['晚餐', '宵夜'],
      cookingStyles: ['韓式']
    },
    // === 西式料理 ===
    {
      id: '39',
      title: '義式燉飯',
      description: '奶油香濃的義式燉飯，米粒吸收高湯精華，每一口都是享受。',
      imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800',
      cookingTime: 40,
      servings: 2,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 680,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-23',
      ingredients: [{ name: '義大利米', amount: '150', unit: '公克' }, { name: '白酒', amount: '50', unit: 'ml' }],
      seasonings: [{ group: 'A', items: [{ name: '帕瑪森起司', amount: '30 公克' }] }],
      steps: [{ stepNumber: 1, description: '洋蔥切丁炒香。' }],
      kitchenware: [],
      tags: ['義式', '燉飯', '奶油'],
      categories: ['異國料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['西式']
    },
    {
      id: '40',
      title: '蒜香蝦義大利麵',
      description: '橄欖油炒出蒜香，鮮甜蝦仁與彈牙麵條的完美結合。',
      imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
      cookingTime: 25,
      servings: 2,
      difficulty: 'easy',
      rating: 4.7,
      ratingCount: 1200,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-22',
      ingredients: [{ name: '義大利麵', amount: '200', unit: '公克' }, { name: '蝦子', amount: '10', unit: '隻' }],
      seasonings: [{ group: 'A', items: [{ name: '橄欖油', amount: '3 大匙' }, { name: '蒜末', amount: '3 瓣' }] }],
      steps: [{ stepNumber: 1, description: '義大利麵煮至彈牙。' }],
      kitchenware: [],
      tags: ['義式', '麵食', '海鮮'],
      categories: ['異國料理', '快速料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['西式']
    },
    {
      id: '41',
      title: '經典漢堡排',
      description: '多汁的手工漢堡排，外焦內嫩，可搭配麵包或直接當主菜。',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
      cookingTime: 30,
      servings: 4,
      difficulty: 'medium',
      rating: 4.6,
      ratingCount: 890,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-21',
      ingredients: [{ name: '牛絞肉', amount: '400', unit: '公克' }, { name: '洋蔥', amount: '1/2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '1 茶匙' }, { name: '黑胡椒', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '絞肉加調味料攪拌至黏性。' }],
      kitchenware: [],
      tags: ['西式', '牛肉', '便當菜'],
      categories: ['異國料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['西式']
    },
    {
      id: '42',
      title: '奶油濃湯',
      description: '香濃滑順的奶油濃湯，加入蘑菇和雞肉，溫暖你的胃。',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
      cookingTime: 35,
      servings: 4,
      difficulty: 'medium',
      rating: 4.5,
      ratingCount: 560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-20',
      ingredients: [{ name: '蘑菇', amount: '200', unit: '公克' }, { name: '鮮奶油', amount: '100', unit: 'ml' }],
      seasonings: [{ group: 'A', items: [{ name: '鹽', amount: '適量' }, { name: '白胡椒', amount: '少許' }] }],
      steps: [{ stepNumber: 1, description: '蘑菇切片炒香。' }],
      kitchenware: [],
      tags: ['西式', '湯品', '奶油'],
      categories: ['異國料理'],
      mealTypes: ['配菜'],
      cookingStyles: ['西式']
    },
    {
      id: '43',
      title: '法式吐司',
      description: '外酥內軟的法式吐司，淋上楓糖漿，甜蜜的早午餐選擇。',
      imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
      cookingTime: 15,
      servings: 2,
      difficulty: 'easy',
      rating: 4.6,
      ratingCount: 780,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-19',
      ingredients: [{ name: '吐司', amount: '4', unit: '片' }, { name: '雞蛋', amount: '2', unit: '顆' }],
      seasonings: [{ group: 'A', items: [{ name: '牛奶', amount: '50 ml' }, { name: '楓糖漿', amount: '適量' }] }],
      steps: [{ stepNumber: 1, description: '蛋液加牛奶拌勻。' }],
      kitchenware: [],
      tags: ['西式', '早餐', '甜點'],
      categories: ['異國料理', '快速料理'],
      mealTypes: ['早餐', '下午茶'],
      cookingStyles: ['西式']
    },
    // === 中式經典 ===
    {
      id: '44',
      title: '宮保雞丁',
      description: '香辣過癮的宮保雞丁，花生的酥脆與雞肉的嫩滑完美搭配。',
      imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800',
      cookingTime: 25,
      servings: 2,
      difficulty: 'medium',
      rating: 4.8,
      ratingCount: 1560,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-18',
      ingredients: [{ name: '雞胸肉', amount: '200', unit: '公克' }, { name: '花生', amount: '50', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '辣椒乾', amount: '10 根' }, { name: '花椒', amount: '1 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞肉切丁醃製。' }],
      kitchenware: [],
      tags: ['川菜', '雞肉', '辣'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '45',
      title: '糖醋排骨',
      description: '酸甜可口的糖醋排骨，外酥內嫩，大人小孩都愛吃。',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      cookingTime: 45,
      servings: 4,
      difficulty: 'medium',
      rating: 4.7,
      ratingCount: 1340,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-17',
      ingredients: [{ name: '排骨', amount: '500', unit: '公克' }],
      seasonings: [{ group: 'A', items: [{ name: '番茄醬', amount: '3 大匙' }, { name: '白醋', amount: '2 大匙' }] }],
      steps: [{ stepNumber: 1, description: '排骨切塊汆燙。' }],
      kitchenware: [],
      tags: ['中式', '糖醋', '豬肉'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '46',
      title: '紅燒牛腩',
      description: '軟爛入味的紅燒牛腩，膠質豐富，配飯配麵都超讚。',
      imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=800',
      cookingTime: 120,
      servings: 6,
      difficulty: 'hard',
      rating: 4.9,
      ratingCount: 1780,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-16',
      ingredients: [{ name: '牛腩', amount: '800', unit: '公克' }, { name: '白蘿蔔', amount: '1', unit: '根' }],
      seasonings: [{ group: 'A', items: [{ name: '醬油', amount: '5 大匙' }, { name: '冰糖', amount: '3 大匙' }] }],
      steps: [{ stepNumber: 1, description: '牛腩切塊汆燙去血水。' }],
      kitchenware: [],
      tags: ['中式', '燉煮', '牛肉'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '47',
      title: '三杯雞',
      description: '台式經典三杯雞，麻油香氣撲鼻，九層塔提味，白飯殺手！',
      imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800',
      cookingTime: 35,
      servings: 3,
      difficulty: 'medium',
      rating: 4.8,
      ratingCount: 1650,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-15',
      ingredients: [{ name: '雞腿', amount: '2', unit: '支' }, { name: '九層塔', amount: '1', unit: '把' }],
      seasonings: [{ group: 'A', items: [{ name: '麻油', amount: '3 大匙' }, { name: '醬油', amount: '3 大匙' }] }],
      steps: [{ stepNumber: 1, description: '雞腿剁塊。' }],
      kitchenware: [],
      tags: ['台式', '雞肉', '下飯'],
      categories: ['家常料理'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    },
    {
      id: '48',
      title: '蒸魚',
      description: '清蒸鮮魚保留原味，搭配薑絲和蔥絲，清爽又健康。',
      imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
      cookingTime: 20,
      servings: 4,
      difficulty: 'easy',
      rating: 4.5,
      ratingCount: 680,
      author: '楊桃美食網美食團隊',
      uploadDate: '2025-11-14',
      ingredients: [{ name: '鱸魚', amount: '1', unit: '尾' }, { name: '薑絲', amount: '適量', unit: '' }],
      seasonings: [{ group: 'A', items: [{ name: '蒸魚醬油', amount: '3 大匙' }] }],
      steps: [{ stepNumber: 1, description: '魚清洗乾淨。' }],
      kitchenware: [],
      tags: ['清蒸', '海鮮', '健康'],
      categories: ['健康飲食'],
      mealTypes: ['午餐', '晚餐'],
      cookingStyles: ['中式']
    }
  ];

  readonly newsArticles: NewsArticle[] = [
    {
      id: '1',
      title: 'AI 食譜體驗正式上線！輸入冰箱食材，三秒就能生成專屬料理建議，今晚吃什麼不再是難題',
      excerpt: 'AI 食譜體驗正式上線！輸入冰箱食材，三秒就能生成專屬料理建議...',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      category: '服務更新',
      publishDate: '2025-12-31'
    },
    {
      id: '2',
      title: '參加楊桃線上一週快煮挑戰，輕鬆完成 7 道快速料理！',
      excerpt: '參加楊桃線上一週快煮挑戰，輕鬆完成 7 道快速料理...',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
      category: '活動企劃',
      publishDate: '2025-12-31'
    },
    {
      id: '3',
      title: '入秋該吃什麼？秋季餐桌新寵！南瓜料理熱潮席捲全網！',
      excerpt: '入秋該吃什麼？秋季餐桌新寵！南瓜料理熱潮席捲全網...',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800',
      category: '美食趨勢',
      publishDate: '2025-12-31'
    },
    {
      id: '4',
      title: '2025 年度最受歡迎食譜 TOP 10 揭曉！',
      excerpt: '2025 年度最受歡迎食譜 TOP 10 揭曉...',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
      category: '美食趨勢',
      publishDate: '2025-12-30'
    },
    {
      id: '5',
      title: '春節年菜預購開跑！楊桃嚴選團圓好滋味',
      excerpt: '春節年菜預購開跑！楊桃嚴選團圓好滋味...',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1547573854-74d2a71d0826?w=800',
      category: '活動企劃',
      publishDate: '2025-12-28'
    }
  ];

  readonly products: Product[] = [
    {
      id: 'p1',
      name: '【PERFECT理想】日式黑金鋼鐵板燒鍋36cm 附蓋(電磁爐可用)',
      brand: 'PERFECT理想',
      imageUrl: 'https://shoplineimg.com/6200f43d76759e003faa9414/65d325a3f574ae00178ca98c/800x.webp?source_format=jpg',
      price: 1280,
      originalPrice: 2880,
      purchaseUrl: 'https://shop.ytower.com.tw/products/ikh-35030',
      isHot: true
    },
    {
      id: 'p2',
      name: '【MEYER美亞】Circulon Total圓滿導磁不沾炒鍋26cm',
      brand: 'MEYER美亞',
      imageUrl: 'https://shoplineimg.com/6200f43d76759e003faa9414/6567243a061a0400146b03fc/800x.webp?source_format=jpg',
      price: 1480,
      originalPrice: 4200,
      purchaseUrl: 'https://shop.ytower.com.tw/products/83923-t',
      isHot: true
    },
    {
      id: 'p3',
      name: '【IKIIKI伊崎】美派烘炸鍋4.0L 玻璃氣炸鍋',
      brand: 'IKIIKI伊崎',
      imageUrl: 'https://shoplineimg.com/6200f43d76759e003faa9414/64787a2b102baa0020f1faf5/800x.webp?source_format=jpg',
      price: 3680,
      originalPrice: 5980,
      purchaseUrl: 'https://shop.ytower.com.tw/products/ik-ot3102',
      isHot: true
    },
    {
      id: 'p4',
      name: '韓國Kassel 晶潤珍珠陶瓷不沾寬底深炒鍋-28cm',
      brand: 'Kassel',
      imageUrl: 'https://shoplineimg.com/6200f43d76759e003faa9414/68afbd3e651700001871b8e9/800x.webp?source_format=jpg',
      price: 1280,
      originalPrice: 3680,
      purchaseUrl: 'https://shop.ytower.com.tw/products/kassel-wokw28'
    }
  ];

  readonly featuredThemes = [
    { title: '健康飲食', description: '健康新選擇，營養均衡的美味料理', imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', slug: 'healthy' },
    { title: '快速料理', description: '忙碌生活中的15分鐘快速上桌料理', imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800', slug: 'quick' },
    { title: '節慶主題', description: '聖誕、新年、中秋等節慶必備料理', imageUrl: 'https://images.unsplash.com/photo-1576402187878-974f70c890a5?w=800', slug: 'festive' },
  ];

  getRecipeById(id: string): Recipe | undefined {
    return this.popularRecipes.find(r => r.id === id);
  }

  getRecipes(): Recipe[] {
    return this.popularRecipes;
  }

  getCategories(): { id: string; title: string; description: string; imageUrl: string }[] {
    return this.categories.map(cat => ({
      id: cat.id,
      title: cat.name,
      description: cat.description || '',
      imageUrl: this.getCategoryImage(cat.slug)
    }));
  }

  private getCategoryImage(slug: string): string {
    const images: Record<string, string> = {
      healthy: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
      quick: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600',
      festive: 'https://images.unsplash.com/photo-1576402187878-974f70c890a5?w=600',
      mealtime: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600',
      budget: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600',
      equipment: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=600',
      family: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600',
      bento: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600',
      seasonal: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600',
      special: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600'
    };
    return images[slug] || 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600';
  }

  getNewsArticles() {
    return this.newsArticles;
  }

  getProducts() {
    return this.products;
  }

  getTopRecipes(count: number = 10) {
    return this.popularRecipes
      .sort((a, b) => b.rating - a.rating)
      .slice(0, count);
  }
}

